[workspace]
members = ["unbound", "unbound-derive"]
resolver = "2"

[workspace.dependencies]
proc-macro2 = "^1.0"
quote = "1.0.42"
syn = { version = "2.0.111", features = [
  "full",
  "extra-traits",
  "visit",
  "visit-mut",
] }
thiserror = "^2.0.17"
